# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ald_TEYfBcB6jkiQ6CNqirQ560QzuSdo
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

pima=pd.read_csv("https://raw.githubusercontent.com/Aditya-Mankar/Diabetes-Prediction/refs/heads/master/diabetes.csv")
pima.columns=pima.columns.str.strip()
print("Columns in dataset:", pima.columns.tolist())
type(pima)

feature_cols = ['Pregnancies', 'Insulin', 'BMI', 'Age', 'Glucose', 'BloodPressure', 'DiabetesPedigreeFunction']
X = pima[feature_cols].astype(float) # Ensure all features are numeric
y = pima['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
logreg = LogisticRegression(random_state=0, solver='lbfgs', max_iter=500)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
y_pred

df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred)
recall = metrics.recall_score(y_test, y_pred)
f1 = metrics.f1_score(y_test, y_pred)

print("Confusion Matrix:\n", cnf_matrix)
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")