# -*- coding: utf-8 -*-
"""task9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_4V1U6f5dq7Un2_F3JpD5V-HLlhQfHj
"""

import pandas as pd
import numpy as np
df = pd.read_csv()
df

df.isnull().sum()
df.dropna(axis=0,inplace=True)
df.isnull().sum()
df.head()

X=df.iloc[ : ,0:4]
y=df.iloc[ : ,-1]
X,y

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train

from sklearn.neighbors import KNeighborsClassifier
KNN_classifier = KNeighborsClassifier(n_neighbors = 5)
KNN_classifier.fit(X_train,y_train)

prediction = KNN_classifier.predict(X_test)
print(prediction)

from sklearn.metrics import accuracy_score,confusion_matrix

confusionMmatrix = confusion_matrix(y_test, prediction)
print(confusionMmatrix)

accuracy_score=accuracy_score(y_test, prediction)
print(accuracy_score)
print('Misclassified samples: ' % (y_test!= prediction).sum())

Misclassified_sample = []
for i in range(1, 20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    Misclassified_sample.append((y_test!= pred_i).sum())
print(Misclassified_sample)

