# -*- coding: utf-8 -*-
"""task12_a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_lyHFswkO-fgOy8NE7O9SzWCsmvla_I
"""

# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Load the iris dataset
iris = load_iris()
X = iris.data

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize and fit K-Means model
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X_scaled)

KMeans(n_clusters=3, random_state=42)

# Predict cluster labels
y_kmeans = kmeans.predict(X_scaled)

# Reduce dimensionality for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Plot the clustered data
plt.figure(figsize=(10, 7))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_kmeans, cmap='viridis', marker='o')
centroids = pca.transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='x', s=200, label='Centroids')
plt.title('K-Means Clustering of Iris Data (PCA-reduced)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.show()

# Print the coordinates of the cluster centers
print("Cluster Centers (after PCA transformation):")
print(centroids)

# written in task12.txt
# o/p:
# Cluster Centers (after PCA transformation):
# [[ 1.72103664  0.60288719]
#  [-2.22475316  0.28892745]
#  [ 0.57262144 -0.80720888]]



