# -*- coding: utf-8 -*-
"""task11_b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtYpaTZE1K-zm65TvWgC6uibq4vjqQsh
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings("ignore")

# Load the dataset
data = load_iris()
X = data.data
y = data.target
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train
y_train

from sklearn.ensemble import AdaBoostClassifier

# Example: using DecisionTreeClassifier as the base
from sklearn.tree import DecisionTreeClassifier
base_estimator = DecisionTreeClassifier(max_depth=1)

ada_clf = AdaBoostClassifier(estimator=base_estimator, n_estimators=50, learning_rate=1.0, random_state=42)
ada_clf.fit(X_train, y_train)

# Make predictions
y_pred = ada_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of AdaBoost classifier: {accuracy * 100:.2f}%")

