# -*- coding: utf-8 -*-
"""task7_docx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IUhjN9qxeisaZ2OPyuKfHN8Yg8RdCKe
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.datasets import load_iris
iris=load_iris()
iris

iris.data
iris.target

import seaborn as sns
df=sns.load_dataset('iris')
df.head()

X=df.iloc[:,:-1]
y=iris.target
X,y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train

from sklearn.tree import DecisionTreeClassifier
treemodel=DecisionTreeClassifier(max_depth=2)
treemodel.fit(X_train,y_train)

from sklearn import tree
plt.figure(figsize=(15,10))
tree.plot_tree(treemodel,filled=True)
plt.show()

y_pred=treemodel.predict(X_test)
y_pred

from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))