# -*- coding: utf-8 -*-
"""task5_b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQ-LvDuB9bzCAxPb4unPBFRHZ09K61RW
"""

import pandas as pd
# import matplotlib.pyplot as plt

!wget https://github.com/krishnaik06/Multiple-Linear-Regression/raw/refs/heads/master/50_Startups.csv
data=pd.read_csv('50_Startups.csv')
data.head()

X=data.iloc[ : ,0:4]
y=data.iloc[:,4]

X.head()

y.head()

states=pd.get_dummies(X['State'],drop_first=True)
# Drop the state coulmn
X=X.drop('State',axis=1)
# concat the dummy variables
X=pd.concat([X,states],axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score
# Assuming you have your true y values (y_test) and predicted y values (y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("Mean Absolute Error (MAE):", mae)
print("R-squared (R2):", r2)



